### ISSUE TITLE
Handle `MESSAGE_DELETE_BULK` event

### ISSUE THREAD

**Issue by IAmFletcher** [IAmFletcher/discord-bot#2]
NOTE: All event data is stored in the `msg.d` object. For example `guild_id` in `MESSAGE_DELETE_BULK` can be accessed via `msg.d.guild_id`.

Event: https://discordapp.com/developers/docs/topics/gateway#message-delete-bulk

- Add a function to `Guild` that loops through `ids` and removes them from the DB
- Add a `gatewayClient.on` for `MESSAGE_DELETE_BULK` to index.js that calls the function
- Use `queryPromise` for any DB queries

(NOTE: I'll be working on more DB helper functions in the next 24 hours. If a relevant one exists, use this instead of `queryPromise`)

**Comment by PranjalAgni** [comment]
Can I work on this?

**Comment by IAmFletcher** [comment]
@PranjalAgni Appreciate the offer, but would prefer to leave this for someone's first contribution.

**Comment by tokarzkj** [comment]
I would be interested on working on this if no one has grabbed it yet

**Comment by PranjalAgni** [comment]
@IAmFletcher How Message table will be created in the database as there is only constants table only

**Comment by IAmFletcher** [comment]
@PranjalAgni Just fixed that in the latest version. Removed it when I added the migration function, and didn't test with a fresh DB. Thanks for pointing it out!

Also, I seem to have gotten confused what `good first issue` means. If you'd like to tackle this, feel free.

@tokarzkj I got confused about what `good first issue` meant when I told Pranjal that I would prefer to leave this for someone's first contribution, so I'm going to open it to him first if he still wants to tackle it.

If not, sure!

**Comment by PranjalAgni** [comment]
Yes I am working on this ✌️

**Comment by PranjalAgni** [comment]
Can you please show a example of how to assign a role by creating a message as `parseMessage()` returns undefined so no messaage gets saved in the database.

**Comment by IAmFletcher** [comment]
I think this is what you're asking about: https://twitter.com/IAmFletcher_/status/1178068993724358662

Make sure the bot role is above any roles you want it to be able to assign.

**Comment by PranjalAgni** [comment]
Can you please verify your `queryPromise()` function, I am getting error in this query `INSERT INTO ${table} (${columns.join(', ')}) VALUES (?)`

**Comment by PranjalAgni** [comment]
I have figured it out the `parseMessage()` function is returning a empty array so  `values` param in `queryPromise()`  is not correct and it throws error.

**Comment by IAmFletcher** [comment]
Yeah, that means one of the Roles in your message does not exist on the server. If it does exist, you need to restart the bot. Once I've pulled in the other PR, this shouldn't be a problem anymore.

**Comment by PranjalAgni** [comment]
Yup! Also it would be great if you set up the eslint so we have consistent style across everyone.

**Comment by IAmFletcher** [comment]
Should have fixed the error in the latest push to master.

We have semistandard in devDependencies. Guessing this isn't working?

**Comment by PranjalAgni** [comment]
So when the `MESSAGE_DELETE_BULK` event happens I need to delete all the messages for that guild_id?

**Comment by IAmFletcher** [comment]
No, you need to use the array of ids (aka message ids).

**Comment by PranjalAgni** [comment]
Okay so I need to get all the `message_id` for that `guild_id` and then delete it from DB

**Comment by IAmFletcher** [comment]
In the event, you get an array of ids unders `message.d.ids`. You can either iterate through them and attempt to delete them individually. Or, if possible, you may be able to bulk delete.

You could even query the DB for all rows attached to the `guild_id`, check the `message_id` column against the array, and only send delete statements for those that match. This would probably be the best solution.

Note: The Guild object stores it's id as `this.id`.

**Comment by PranjalAgni** [comment]
Yes I have implemented the second solution :)

**Comment by PranjalAgni** [comment]
Please configure a linter it will help keep everyone on the same page.

**Comment by IAmFletcher** [comment]
That's on the task list for tonight. Thanks again for the PR!

**Comment by PranjalAgni** [comment]
Thanks for helping me out through the process it was a new experience for me working on a Discord bot 👍.

**Comment by IAmFletcher** [comment]
Merged in #7
